# Basic Information 
title: Yaoyao Liu
position: Assistant Professor
affiliation: University of Illinois Urbana-Champaign
affiliation_link: https://www.illinois.edu/
affiliation_logo: ./assets/img/illinois.svg
email: lyy (at) illinois.edu

# Search Engine Optimization (SEO)
keywords: yaoyao liu, liu yaoyao, yaoyaoliu, liuyaoyao
canonical: https://yaoyaoliu.web.illinois.edu
description: Yaoyao Liu is an assistant professor at UIUC. His research lies in meta-learning, incremental learning, and image generation.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=Qi2PSmEAAAAJ
github_link: https://github.com/yaoyao-liu/
linkedin: https://www.linkedin.com/in/liuyaoyao/
twitter: https://twitter.com/YaoyaoLiu1/

# Images 
avatar: https://img.yliu.me/avatar_new.jpg

# Footnotes
footnote: Feel free to use my website's source code.
footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: CJD8XwsJhSyQ6sbsU-Gw0cNcUlbah7KW3xvHN2QlwW0

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
